/**
 * NEXO · GUÍA DEL MÓDULO: tests/admin-access.test.js
 * Pruebas unitarias y de integración de admin access.
 * Entrada: Casos y fixtures definidos en este archivo; dependencias simuladas cuando se inyectan.
 * Salida: Aserciones aprobadas o fallo con ubicación; los E2E pueden generar capturas locales.
 * Estado importante: fixture prepara escenario; assert compara resultado esperado; limpieza de
 * recursos evita contaminación entre casos.
 * Efectos y límites: Revisar fixtures y proveedores inyectados antes de ejecutar; los dobles
 * aíslan servicios externos. No usar la base de producción como fixture.
 * Ruta de aprendizaje: docs/23-manual-desarrollador-junior.md y docs/41-mapa-codigo-fuente.md.
 */

import test from 'node:test';
import assert from 'node:assert/strict';
import {once} from 'node:events';
import {mkdtempSync,writeFileSync,rmSync,readFileSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join,resolve,sep} from 'node:path';
import {DatabaseSync} from 'node:sqlite';
import {createRepository} from '../server/db.js';
import {AdminAuth} from '../server/admin-auth.js';
import {AdminMailer} from '../server/providers/admin-mail.js';
import {readInstallation} from '../server/installation.js';
import {SqliteFaqRepository} from '../server/sqlite-faq.js';
import {createApp} from '../server/app.js';
import {schoolCenter} from '../server/center.js';
const email='admin@example.test',ip='127.0.0.1',installation={email,mode:'auto'};
const seed=new URL('../conocimiento/preguntas-frecuentes.txt',import.meta.url);
function directory(t){const path=mkdtempSync(join(tmpdir(),'nexo-access-'));t.after(()=>{assert.ok(resolve(path).startsWith(resolve(tmpdir())+sep)&&path.includes('nexo-access-'));rmSync(path,{recursive:true,force:true});});return path;}
function fixture(t,options={}){const repo=options.repo||createRepository(':memory:');let time=100000000;const messages=[],mailer={ready:true,async sendCode(message){messages.push(message);if(options.fail)throw new Error('Test SMTP failure');},close(){}};const auth=new AdminAuth({repository:repo,installation,mailer,now:()=>time});t.after(async()=>{await auth.close();if(!options.repo)repo.close();});return{repo,auth,mailer,messages,advance:ms=>time+=ms,now:()=>time,async code(address=email){const r=await auth.requestCode(address,ip);await Promise.all([...auth.pending]);return {id:r.challenge,code:messages.at(-1)?.code,response:r};}};}
test('correo válido produce un código de un uso y sesión protegida',async t=>{const f=fixture(t),c=await f.code();assert.equal(f.messages.length,1);assert.equal(f.messages[0].to,email);assert.match(c.code,/^\d{8}$/);assert.ok(!JSON.stringify(c.response).includes(c.code));const token=await f.auth.verify(c.id,c.code,ip);assert.ok(f.auth.authenticated({headers:{cookie:'nexo_admin='+token}}));await assert.rejects(f.auth.verify(c.id,c.code,ip),{status:401});assert.match(f.auth.cookie(token,true),/HttpOnly; SameSite=Strict; Path=\/api;.*Secure/);});
test('dirección ajena no envía correo ni revela si existe',async t=>{const f=fixture(t),c=await f.code('someone@example.test');assert.equal(f.messages.length,0);assert.equal(c.response.resendSeconds,60);await assert.rejects(f.auth.verify(c.id,'00000000',ip));assert.equal(c.response.message,(await f.code()).response.message);});
test('cinco fallos bloquean incluso el código correcto',async t=>{const f=fixture(t),c=await f.code(),bad=c.code==='00000000'?'11111111':'00000000';for(let n=0;n<5;n++)await assert.rejects(f.auth.verify(c.id,bad,ip));await assert.rejects(f.auth.verify(c.id,c.code,ip));});
test('código vencido a los diez minutos no autentica',async t=>{const f=fixture(t),c=await f.code();f.advance(600000);await assert.rejects(f.auth.verify(c.id,c.code,ip));});
test('nuevo código invalida el anterior y limita reenvíos',async t=>{const f=fixture(t),a=await f.code();await f.code();assert.equal(f.messages.length,1);f.advance(61000);const b=await f.code();assert.equal(f.messages.length,2);await assert.rejects(f.auth.verify(a.id,a.code,ip));assert.ok(await f.auth.verify(b.id,b.code,ip));});
test('dos verificaciones simultáneas consumen el código solo una vez',async t=>{const f=fixture(t),c=await f.code();const results=await Promise.allSettled([f.auth.verify(c.id,c.code,ip),f.auth.verify(c.id,c.code,ip)]);assert.equal(results.filter(r=>r.status==='fulfilled').length,1);});
test('sesión vence por inactividad y logout revoca inmediatamente',async t=>{const f=fixture(t),c=await f.code(),token=await f.auth.verify(c.id,c.code,ip),req={headers:{cookie:'nexo_admin='+token}};f.advance(300000);assert.equal(f.auth.authenticated(req),false);const d=await f.code(),next=await f.auth.verify(d.id,d.code,ip),r={headers:{cookie:'nexo_admin='+next}};f.auth.logout(r);assert.equal(f.auth.authenticated(r),false);});
test('sesión tiene vencimiento absoluto aunque haya actividad',async t=>{const f=fixture(t),c=await f.code(),token=await f.auth.verify(c.id,c.code,ip),req={headers:{cookie:'nexo_admin='+token}};for(let n=0;n<119;n++){f.advance(240000);assert.ok(f.auth.authenticated(req));}f.advance(240000);assert.equal(f.auth.authenticated(req),false);});
test('fallo de SMTP no crea código verificable ni anuncia entrega',async t=>{const f=fixture(t,{fail:true}),c=await f.code();assert.match(c.response.message,/Si el correo/);await assert.rejects(f.auth.verify(c.id,c.code,ip));});
test('SQLite guarda verificadores, conserva sesión y límites al reiniciar',async t=>{const path=join(directory(t),'access.sqlite');let repo=createRepository(path);const f=fixture(t,{repo});const c=await f.code();const db=new DatabaseSync(path);const stored=db.prepare('SELECT * FROM admin_challenges').get();assert.notEqual(stored.codeHash,c.code);assert.equal(stored.codeHash.length,128);const token=await f.auth.verify(c.id,c.code,ip);assert.notEqual(db.prepare('SELECT tokenHash FROM admin_sessions').get().tokenHash,token);db.close();await f.auth.close();repo.close();repo=createRepository(path);const restarted=new AdminAuth({repository:repo,installation,mailer:f.mailer,now:f.now});assert.ok(restarted.authenticated({headers:{cookie:'nexo_admin='+token}}));await restarted.requestCode(email,ip);await restarted.close();assert.equal(f.messages.length,1);repo.close();});
test('cambiar administrador invalida accesos anteriores',async t=>{const f=fixture(t),c=await f.code(),token=await f.auth.verify(c.id,c.code,ip);const changed=new AdminAuth({repository:f.repo,installation:{email:'new@example.test',mode:'email'},mailer:f.mailer,now:f.now});assert.equal(changed.authenticated({headers:{cookie:'nexo_admin='+token}}),false);await changed.close();});
test('límite de cinco correos por hora persiste',async t=>{const f=fixture(t);for(let n=0;n<6;n++){await f.code();f.advance(61000);}assert.equal(f.messages.length,5);});
test('configuración y correo no exponen credenciales ni permiten direcciones inválidas',t=>{const folder=directory(t),path=join(folder,'installation.json');writeFileSync(path,JSON.stringify({administratorEmail:email}));const result=readInstallation({SMTP_PASSWORD:'local-secret'},path);assert.equal(result.email,email);assert.equal(result.mail.password,'local-secret');assert.equal(result.mail.secure,true);writeFileSync(path,'null');assert.throws(()=>readInstallation({},path));writeFileSync(path,JSON.stringify({administratorEmail:'bad\r\nBcc: other'}));assert.throws(()=>readInstallation({},path));});
test('SMTP requiere TLS, desactiva logs y rechaza entrega no aceptada',async()=>{let options,payload;const m=new AdminMailer({host:'smtp.example.test',port:587,secure:false,from:email,user:email,password:'secret'},o=>{options=o;return{async sendMail(v){payload=v;return {accepted:[]};},close(){}};});await assert.rejects(m.sendCode({to:email,code:'12345678'}));assert.equal(options.requireTLS,true);assert.equal(options.tls.rejectUnauthorized,true);assert.equal(options.logger,false);assert.equal(options.disableFileAccess,true);assert.equal(payload.to,email);assert.ok(!payload.text.includes('secret'));});
test('FAQ importa una sola vez y SQLite conserva edición sin archivo original',async t=>{const folder=directory(t),path=join(folder,'knowledge.sqlite'),source=join(folder,'seed.txt');writeFileSync(source,readFileSync(seed));let repo=createRepository(path),faq=new SqliteFaqRepository(repo,source);await faq.refresh();assert.equal(faq.status().entries,24);const initial=repo.readKnowledge('school');assert.ok(repo.saveKnowledge('school',initial.revision,'[nuevo]\npregunta: ¿Mi pregunta?\nrespuesta: Respuesta guardada.'));assert.equal(repo.saveKnowledge('school',initial.revision,'Sobrescritura'),null);repo.close();rmSync(source);repo=createRepository(path);faq=new SqliteFaqRepository(repo,source);await faq.refresh();assert.equal(faq.status().entries,1);assert.match(repo.readKnowledge('school').source,/guardada/);repo.close();});
async function apiFixture(t){const repo=createRepository(':memory:'),faq=new SqliteFaqRepository(repo,seed);await faq.refresh();const sent=[];const app=createApp({repository:repo,faq,config:{center:schoolCenter,provider:'demo',adminToken:'legacy-key-that-must-be-rejected',installation,sessionTtlMs:300000},ai:{async reply(){throw new Error('No AI allowed');}},adminMailer:{ready:true,async sendCode(v){sent.push(v);},close(){}},localTts:{status:()=>({available:false}),close(){},stop(){}},liveAvatar:{status:()=>({configured:false}),async close(){},async stop(){}}});app.listen(0,'127.0.0.1');await once(app,'listening');t.after(async()=>{await new Promise(r=>app.close(r));await app.closeAdminAuth();repo.close();});const base='http://127.0.0.1:'+app.address().port;async function request(path,method='GET',body,cookie='',headers={}){const response=await fetch(base+path,{method,headers:{'Content-Type':'application/json',Cookie:cookie,...headers},...(body?{body:JSON.stringify(body)}:{})});return{status:response.status,data:await response.json(),cookie:response.headers.get('set-cookie')};}return{repo,request,sent};}
test('API: cookie autoriza, Bearer anterior se rechaza, logout revoca',async t=>{const f=await apiFixture(t);assert.equal((await f.request('/api/admin/overview','GET',null,'',{Authorization:'Bearer legacy-key-that-must-be-rejected'})).status,401);const cfg=await f.request('/api/auth/config');assert.equal(cfg.data.mode,'email');assert.ok(!JSON.stringify(cfg.data).includes(email));const c=await f.request('/api/auth/request','POST',{email});await new Promise(r=>setImmediate(r));const v=await f.request('/api/auth/verify','POST',{challenge:c.data.challenge,code:f.sent[0].code});assert.equal(v.status,200);const cookie=v.cookie.split(';')[0];assert.match(v.cookie,/HttpOnly; SameSite=Strict/);assert.equal((await f.request('/api/admin/overview','GET',null,cookie)).status,200);assert.equal((await f.request('/api/auth/logout','POST',{},cookie)).status,200);assert.equal((await f.request('/api/admin/overview','GET',null,cookie)).status,401);});
test('API: FAQ exige acceso, valida formato y evita conflictos de revisión',async t=>{const f=await apiFixture(t);assert.equal((await f.request('/api/admin/knowledge')).status,401);const c=await f.request('/api/auth/request','POST',{email});await new Promise(r=>setImmediate(r));const v=await f.request('/api/auth/verify','POST',{challenge:c.data.challenge,code:f.sent[0].code}),cookie=v.cookie.split(';')[0];const original=(await f.request('/api/admin/knowledge','GET',null,cookie)).data;assert.equal((await f.request('/api/admin/knowledge','PUT',{source:'Inválido',revision:original.revision},cookie)).status,400);const change={source:'[nuevo]\npregunta: Hola pregunta\nrespuesta: Hola respuesta',revision:original.revision};assert.equal((await f.request('/api/admin/knowledge','PUT',change,cookie)).status,200);assert.equal((await f.request('/api/admin/knowledge','PUT',change,cookie)).status,409);assert.equal((await f.request('/api/admin/knowledge','GET',null,cookie)).data.source,change.source);});

test('dos administradores reciben códigos independientes y retirar uno conserva al otro',async t=>{
 const repo=createRepository(':memory:');t.after(()=>repo.close());const sent=[];let now=10000000;
 const mailer={ready:true,async sendCode(message){sent.push(message);},close(){}};
 const other='second@example.test';const auth=new AdminAuth({repository:repo,installation:{emails:[email,other],mode:'email'},mailer,now:()=>now});
 const a=await auth.requestCode(email,ip),b=await auth.requestCode(other,ip);await Promise.all([...auth.pending]);assert.equal(sent.length,2);
 await assert.rejects(auth.verify(a.challenge,sent[1].code===sent[0].code?'invalid':sent[1].code,ip));
 const ta=await auth.verify(a.challenge,sent[0].code,ip),tb=await auth.verify(b.challenge,sent[1].code,ip);
 const ra={headers:{cookie:'nexo_admin='+ta}},rb={headers:{cookie:'nexo_admin='+tb}};assert.ok(auth.authenticated(ra));assert.ok(auth.authenticated(rb));
 now+=61000;await auth.requestCode(other,ip);await Promise.all([...auth.pending]);assert.equal(sent.at(-1).to,other);
 const changed=new AdminAuth({repository:repo,installation:{emails:[email],mode:'email'},mailer,now:()=>now});assert.ok(changed.authenticated(ra));assert.equal(changed.authenticated(rb),false);await changed.close();await auth.close();
});

test('migra base de administrador único conservando claves foráneas y sesión existente',async t=>{
 const path=join(directory(t),'legacy.sqlite');let repo=createRepository(path);repo.synchronizeAdministrator(email,1000);repo.close();
 const db=new DatabaseSync(path);db.exec('PRAGMA foreign_keys=OFF; BEGIN; CREATE TABLE legacy_administrators(id INTEGER PRIMARY KEY CHECK(id=1),email TEXT NOT NULL UNIQUE,updatedAt INTEGER NOT NULL) STRICT; INSERT INTO legacy_administrators SELECT * FROM administrators; DROP TABLE administrators; ALTER TABLE legacy_administrators RENAME TO administrators; COMMIT;');db.prepare('INSERT INTO admin_sessions VALUES(?,?,?,?,?)').run('a'.repeat(64),1,1000,100000,200000);db.close();
 repo=createRepository(path);repo.synchronizeAdministrators([email,'second@example.test'],2000);assert.ok(repo.authenticateAdministrator('a'.repeat(64),3000,1000));repo.close();
 const migrated=new DatabaseSync(path);assert.equal(migrated.prepare('SELECT count(*) n FROM administrators').get().n,2);assert.deepEqual(migrated.prepare('PRAGMA foreign_key_check').all(),[]);migrated.close();
});

test('lista de administradores normaliza y rechaza configuración inválida',t=>{
 const path=join(directory(t),'installation.json');writeFileSync(path,JSON.stringify({administratorEmails:['ADMIN@example.test','second@example.test','admin@example.test']}));
 assert.deepEqual(readInstallation({},path).emails,[email,'second@example.test']);
 for(const value of ['someone@example.test',[null],['bad'],Array(11).fill(email)]){writeFileSync(path,JSON.stringify({administratorEmails:value}));assert.throws(()=>readInstallation({},path));}
});
