/**
 * NEXO · GUÍA DEL MÓDULO: tests/booking-transfers.e2e.js
 * Navegador aislado: conflictos, deshabilitar, lote explícito, resultado incierto y recuperación.
 * SQLite real con Calendar simulado; no mueve citas externas, SMTP ni sesiones de video.
 */
import assert from 'node:assert/strict';import {once} from 'node:events';import {createRequire} from 'node:module';import {mkdirSync} from 'node:fs';
import {instructorsFixture} from './instructors-fixture.js';import {createApp} from '../server/app.js';import {schoolCenter} from '../server/center.js';
const {chromium}=createRequire(import.meta.url)(process.env.PLAYWRIGHT_MODULE||'playwright');
const f=await instructorsFixture({now:Date.now}),a=await f.bookings.availability('road-test'),[source,target]=a.instructors;
const first=await f.bookings.reserve(f.input(a.slots[0],source.id)),second=await f.bookings.reserve(f.input(a.slots[1],source.id)),conflict=await f.bookings.reserve(f.input(a.slots[1],target.id)),adminToken='transfer-browser-admin-test';
const app=createApp({repository:f.repo,calendar:f.service,config:{provider:'demo',center:schoolCenter,adminToken},ai:{reply:async()=>{throw Error('No AI');}},localTts:{status:()=>({available:false}),stop(){},close(){}}});app.listen(0,'127.0.0.1');await once(app,'listening');
const browser=await chromium.launch({headless:true,channel:process.env.BROWSER_CHANNEL||'msedge'});
try{const page=await browser.newPage({viewport:{width:1100,height:1000}}),errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('dialog',d=>d.accept());await page.goto('http://127.0.0.1:'+app.address().port+'/admin');await page.locator('#token').fill(adminToken);await page.locator('#login button').click();await page.waitForSelector('#appointments tr');
 await page.locator('#agenda-transfer').click();await page.locator('#transfer-source').selectOption(source.id);await page.locator('#transfer-target').selectOption(target.id);await page.locator('#transfer-reason').fill('Profesor no disponible');await page.locator('#transfer-pause').check();await page.locator('#transfer-preview').click();await page.waitForSelector('.transfer-item');assert.equal(await page.locator('.transfer-item input:not(:disabled)').count(),1);assert.equal(await page.locator('.transfer-item input:disabled').count(),1);assert.equal(f.repo.calendarBooking(first.id).instructorId,source.id);
 await page.setViewportSize({width:390,height:844});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));mkdirSync('.local/transfers-qa',{recursive:true});await page.locator('#transfer-dialog').screenshot({path:'.local/transfers-qa/preview-mobile.png'});
 await page.locator('.transfer-item input:not(:disabled)').check();await page.locator('#transfer-confirm').click();await page.waitForFunction(()=>document.querySelector('#transfer-content').textContent.includes('Proceso terminado'));assert.equal(f.repo.calendarBooking(first.id).instructorId,target.id);assert.equal(f.repo.calendarBooking(second.id).instructorId,source.id);assert.equal(f.repo.bookingSettings().instructors.find(i=>i.id===source.id).active,false);assert.equal(f.events.size,3);
 await f.bookings.cancel(conflict.id);f.flags.patchFails=true;await page.locator('#transfer-preview').click();await page.waitForFunction(()=>document.querySelectorAll('.transfer-item input:not(:disabled)').length===1);await page.locator('.transfer-item input:not(:disabled)').check();await page.locator('#transfer-confirm').click();await page.waitForFunction(()=>document.querySelector('#transfer-preview-list').textContent.includes('Por verificar'));assert.ok(f.repo.pendingBookingTransfer(second.id));
 await page.locator('#transfer-close').click();await page.locator('#appointments tr').filter({hasText:second.code}).getByRole('button',{name:'Ver detalle',exact:true}).click();await page.getByRole('button',{name:'Verificar traslado',exact:true}).waitFor();f.flags.patchFails=false;await page.getByRole('button',{name:'Verificar traslado',exact:true}).click();await page.waitForFunction(()=>!document.querySelector('#appointment-dialog').open);assert.equal(f.repo.pendingBookingTransfer(second.id),null);assert.equal(f.repo.calendarBooking(second.id).instructorId,target.id);assert.equal(f.calls.filter(c=>c.path.endsWith('/move')).length,2);
 await page.locator('#agenda-transfer').click();await page.locator('#transfer-source').waitFor();await page.evaluate(()=>document.querySelector('#transfer-dialog').close());await page.locator('#logout').click();assert.equal(await page.locator('#transfer-content').innerText(),'');assert.deepEqual(errors,[]);console.log('Traslados E2E: vista previa, conflictos, pausa, traslado seleccionado, error de marca, recuperación, móvil y logout aprobados.');
}finally{await browser.close();await new Promise(resolve=>app.close(resolve));await app.closeAdminAuth();f.close();}
