/**
 * NEXO · GUÍA DEL MÓDULO: tests/booking.e2e.js
 * E2E de navegador de booking.
 * Entrada: Casos y fixtures definidos en este archivo; dependencias simuladas cuando se inyectan.
 * Salida: Aserciones aprobadas o fallo con ubicación; los E2E pueden generar capturas locales.
 * Estado importante: fixture prepara escenario; assert compara resultado esperado; limpieza de
 * recursos evita contaminación entre casos.
 * Efectos y límites: Revisar fixtures y proveedores inyectados antes de ejecutar; los dobles
 * aíslan servicios externos. No usar la base de producción como fixture.
 * Ruta de aprendizaje: docs/23-manual-desarrollador-junior.md y docs/41-mapa-codigo-fuente.md.
 */

import assert from 'node:assert/strict';
import {once} from 'node:events';
import {pcmToWav} from '../server/providers/local-tts.js';
import {createRequire} from 'node:module';
import {mkdirSync} from 'node:fs';
import {join} from 'node:path';
import {createApp} from '../server/app.js';
import {BookingService} from '../server/booking.js';
import {centerRepository,schoolCenter} from '../server/center.js';
import {calendarFixture} from './calendar-fixture.js';
const {chromium}=createRequire(import.meta.url)(process.env.PLAYWRIGHT_MODULE||'playwright');
const f=calendarFixture(),adminToken='booking-browser-test-token';await f.authorize();await f.service.select(f.calendars[1].id);
const repo=centerRepository(f.repo,schoolCenter);repo.saveService(repo.getCenterSettings().revision,'road-test',{name:'Clase práctica',description:'Clase individual de conducción.',duration:60,priceCents:null,requirements:null,modality:'Presencial',active:true});
const busySlots=[];const original=f.service.fetch;f.service.fetch=async(url,opts)=>opts.method==='GET'&&new URL(url).pathname.endsWith('/events')?new Response(JSON.stringify({items:[...f.events.values(),...busySlots]})):original(url,opts);
const booking=new BookingService({repository:repo,calendar:f.service});await booking.configure({...repo.bookingSettings(),enabled:true,serviceIds:['road-test']});
const initialSchedule=await booking.availability('road-test');const busyStart=initialSchedule.slots[2];busySlots.push({summary:'Private event title',start:{dateTime:busyStart},end:{dateTime:new Date(Date.parse(busyStart)+3600000).toISOString()}});
const fullDay=initialSchedule.slots.at(-1).slice(0,10);busySlots.push({start:{date:fullDay},end:{date:new Date(Date.parse(fullDay+'T00:00:00Z')+86400000).toISOString().slice(0,10)}});
const mails=[],videoStops=[];
const app=createApp({bookingMailer:{ready:true,async sendConfirmation(value){mails.push(value);},close(){}},repository:f.repo,calendar:f.service,config:{provider:'demo',center:schoolCenter,adminToken,sessionTtlMs:300000},ai:{reply:async()=>{throw Error('No AI calls expected');}},localTts:{status:()=>({available:true}),stop(){},close(){},synthesize:async()=>({audioBase64:pcmToWav(Buffer.alloc(4410)).toString('base64')})},liveAvatar:{status:()=>({configured:true,paidEnabled:true,mode:'LITE',requirements:{key:true,avatar:true}}),start:async()=>({id:'test',integrationMode:'LITE',websocketUrl:'wss://test.local',roomUrl:'wss://test.local',roomToken:'mock',expiresAt:Date.now()+60000}),stop:async()=>{videoStops.push(true);return {stopped:true};},close:async()=>{}}});app.listen(0,'127.0.0.1');await once(app,'listening');const base='http://127.0.0.1:'+app.address().port;
const browser=await chromium.launch({headless:true,channel:process.env.BROWSER_CHANNEL||'msedge'});
try{
 const page=await browser.newPage({viewport:{width:1360,height:1000}}),errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('dialog',d=>d.accept());
 const chats=[];page.on('request',r=>{if(r.url().endsWith('/api/chat'))chats.push(r.postData());});
 await page.addInitScript(()=>{window.__starts=0;class Recognition{start(){window.__starts++;window.__recognition=this;this.active=true;this.onstart?.();}abort(){this.active=false;this.onend?.();}}window.SpeechRecognition=Recognition;});
 await page.goto(base);await page.locator('#home-services').click();await page.locator('.service-card').filter({hasText:'Clase práctica'}).click();assert.equal(await page.locator('#booking-title').innerText(),'Mi cita y horarios');assert.match(await page.locator('#booking-content').innerText(),/Clase práctica/);assert.equal(await page.locator('#booking-content > button').count(),3);assert.equal(await page.locator('body.voice-call, body.video-first').count(),0);
 await page.getByRole('button',{name:'Consultar mi cita',exact:true}).click();await page.locator('#welcome-dialog button[aria-label="Cerrar"]').click();assert.equal(await page.locator('#booking-content [name="email"]').count(),0);
 await page.getByRole('button',{name:'Ver disponibilidad',exact:true}).click();await page.locator('#accept-session').click();await page.waitForSelector('.slot');assert.match(await page.locator('#booking-title').innerText(),/Disponibilidad/);assert.equal(f.events.size,0);
 await page.keyboard.press('Escape');await page.locator('.service-card').filter({hasText:'Clase práctica'}).click();await page.getByRole('button',{name:'Reservar y confirmar cita',exact:true}).click();await page.waitForSelector('.slot');
 assert.equal(await page.locator('.slot[data-availability=occupied]').count(),1);assert.equal(await page.locator('.slot[data-availability=occupied]').isDisabled(),true);assert.match(await page.locator('.slot[data-availability=occupied]').innerText(),/Ocupado/);assert.doesNotMatch(await page.locator('#booking-content').innerText(),/Private event title/);
 if(process.env.SCREENSHOT_DIR){mkdirSync(process.env.SCREENSHOT_DIR,{recursive:true});await page.locator('#booking-dialog').screenshot({path:join(process.env.SCREENSHOT_DIR,'horarios-estados.png')});}
 await page.locator('#booking-day').selectOption({index:(await page.locator('#booking-day option').count())-1});assert.equal(await page.locator('.slot:not(:disabled)').count(),0);assert.match(await page.locator('.slot-container').innerText(),/No quedan horarios disponibles/);await page.locator('#booking-day').selectOption({index:0});
 assert.match(await page.locator('.booking-summary').innerText(),/60 minutos/);assert.doesNotMatch(await page.locator('.booking-summary').innerText(),/ejemplo/);
 await page.locator('.slot:not(:disabled)').first().click();await page.locator('[name="customerName"]').fill('Alumno Prueba');await page.locator('[name="email"]').fill('alumno@example.test');await page.locator('[name="consent"]').check();
 await page.getByRole('button',{name:'Revisar turno'}).click();assert.match(await page.locator('#booking-content').innerText(),/agenda del negocio/);await page.getByRole('button',{name:'Confirmar turno'}).click();await page.waitForSelector('.receipt-code');assert.equal(f.repo.calendarBookings()[0].status,'reserved');assert.equal(mails.length,1);assert.equal(await page.locator('.receipt-code').innerText(),f.repo.calendarBookings()[0].code);assert.match(await page.locator('#booking-content').innerText(),/Confirmación enviada a alumno@example.test/);assert.match(await page.locator('#booking-content').innerText(),/registrada en Google Calendar/);
 const homeBooking=f.repo.calendarBookings()[0];await page.getByRole('button',{name:'Finalizar atención'}).click();await page.locator('#home-services').click();await page.locator('.service-card').filter({hasText:'Clase práctica'}).click();await page.getByRole('button',{name:'Consultar mi cita',exact:true}).click();await page.locator('#accept-session').click();await page.locator('[name="email"]').fill('alumno@example.test');await page.locator('[name="id"]').fill(homeBooking.code);await page.getByRole('button',{name:'Consultar cita',exact:true}).click();await page.waitForFunction(()=>document.querySelector('#booking-content').textContent.includes('Cita confirmada en Google Calendar'));await page.getByRole('button',{name:'Volver al inicio',exact:true}).click();assert.equal(await page.locator('#booking-dialog').evaluate(el=>el.open),false);
 await page.goto(base+'/admin');await page.locator('#token').fill(adminToken);await page.locator('#login button').click();await page.waitForSelector('#appointments tr');assert.match(await page.locator('#appointments').innerText(),/Alumno Prueba/);
 await page.getByRole('button',{name:'Cancelar',exact:true}).click();await page.locator('#cancel-appointment-form [name=reason]').selectOption('Error al crear la reserva');await page.getByRole('button',{name:'Confirmar cancelación',exact:true}).click();await page.waitForFunction(()=>document.querySelector('#appointments').textContent.includes('Cancelado'));assert.equal(f.events.size,0);
 // Reserve inside a voice call: recognition must stop before personal fields appear.
 await page.goto(base);await page.locator('#start').click();await page.locator('#accept-session').click();await page.waitForFunction(()=>document.querySelector('#mic').getAttribute('aria-pressed')==='true');
 await page.evaluate(()=>{const r=window.__recognition,result=[{transcript:'Quiero ver disponibilidad'}];result.isFinal=true;r.onresult({results:[result]});r.onend?.();});await page.waitForSelector('#booking-day');assert.match(await page.locator('#booking-title').innerText(),/Disponibilidad/);assert.equal(f.events.size,0);assert.equal(await page.evaluate(()=>window.__recognition.active),false);assert.equal(await page.locator('body.voice-call').count(),1);
 await page.keyboard.press('Escape');await page.waitForFunction(()=>document.querySelector('#mic').getAttribute('aria-pressed')==='true');
 // A visitor who paused the mic keeps that choice after closing the form.
 await page.locator('#call-mic').click();await page.locator('#call-booking').click();await page.getByRole('button',{name:'Reservar y confirmar cita',exact:true}).click();await page.waitForSelector('.slot');await page.keyboard.press('Escape');assert.equal(await page.locator('#mic').getAttribute('aria-pressed'),'false');await page.locator('#call-mic').click();
 await page.waitForFunction(()=>document.querySelector('#mic').getAttribute('aria-pressed')==='true');await page.locator('#call-booking').click();await page.getByRole('button',{name:'Reservar y confirmar cita',exact:true}).click();await page.waitForSelector('#booking-day');
 await page.locator('#booking-day').selectOption({index:1});await page.locator('.slot:not(:disabled)').first().click();
 await page.setViewportSize({width:390,height:844});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));
 await page.locator('[name="customerName"]').fill('Persona de voz');await page.locator('[name="email"]').fill('correo-invalido');await page.locator('[name="consent"]').check();await page.getByRole('button',{name:'Revisar turno'}).click();assert.equal(await page.getByRole('button',{name:'Confirmar turno'}).count(),0);
 await page.locator('[name="email"]').fill('voz@example.test');assert.equal(await page.locator('[name="email"]').getAttribute('inputmode'),'email');assert.equal(await page.evaluate(()=>window.__recognition.active),false);assert.equal(f.events.size,0);
 if(process.env.SCREENSHOT_DIR){mkdirSync(process.env.SCREENSHOT_DIR,{recursive:true});await page.screenshot({path:join(process.env.SCREENSHOT_DIR,'voice-booking-form.png')});}
 await page.getByRole('button',{name:'Revisar turno'}).click();assert.match(await page.locator('#booking-content').innerText(),/voz@example.test/);await page.getByRole('button',{name:'Confirmar turno'}).click();await page.waitForSelector('.receipt-code');assert.equal(f.events.size,1);assert.ok(chats.length>=1);assert.ok(chats.every(text=>!text.includes('voz@example.test')&&!text.includes('Persona de voz')));
 await page.getByRole('button',{name:'Volver a la llamada'}).click();await page.waitForFunction(()=>document.querySelector('#mic').getAttribute('aria-pressed')==='true');assert.equal(await page.locator('[name="email"]').count(),0);
 assert.equal(mails.length,2);
 const savedVoice=f.repo.calendarBookings().find(r=>r.customerName==='Persona de voz');assert.match(savedVoice.code,/^[A-Z]{4}-[A-Z]{4}$/);
 await page.locator('#call-booking').click();await page.getByRole('button',{name:'Consultar mi cita',exact:true}).click();await page.locator('[name="email"]').fill('wrong@example.test');await page.locator('[name="id"]').fill(savedVoice.code.toLowerCase().replace('-',' '));await page.getByRole('button',{name:'Consultar cita',exact:true}).click();await page.waitForFunction(()=>document.querySelector('#booking-content .notice').textContent.includes('No encontramos'));assert.equal(await page.locator('#booking-content').innerText().then(t=>t.includes('Clase práctica')),false);
 await page.locator('[name="email"]').fill('voz@example.test');await page.getByRole('button',{name:'Consultar cita',exact:true}).click();await page.waitForFunction(()=>document.querySelector('#booking-content').textContent.includes('Cita confirmada en Google Calendar'));await page.getByRole('button',{name:'Volver a la llamada'}).click();
 await page.locator('#call-hangup').click();assert.equal(await page.locator('body.voice-call').count(),0);assert.equal(await page.evaluate(()=>window.__recognition.active),false);
 const last=f.repo.calendarBookings().find(r=>r.customerName==='Persona de voz');await booking.cancel(last.id);
 // Multiple eligible services present a chooser inside the same call.
 await booking.configure({...repo.bookingSettings(),serviceIds:['road-test','cinco-horas']});await page.goto(base);await page.locator('#start').click();await page.locator('#accept-session').click();await page.waitForFunction(()=>document.querySelector('#mic').getAttribute('aria-pressed')==='true');await page.locator('#call-booking').click();await page.getByRole('button',{name:'Reservar y confirmar cita',exact:true}).click();await page.getByRole('button',{name:'Clase práctica · 60 min',exact:true}).click();await page.waitForSelector('.slot');assert.equal(await page.evaluate(()=>window.__recognition.active),false);
 // Inactivity still clears the form and never reopens recognition after reset.
 const starts=await page.evaluate(()=>window.__starts);await page.evaluate(()=>{const now=Date.now.bind(Date);Date.now=()=>now()+61000;});await page.waitForFunction(()=>!document.body.classList.contains('voice-call'));assert.equal(await page.locator('[name="email"]').count(),0);assert.equal(await page.evaluate(()=>window.__starts),starts);
 await page.setViewportSize({width:1360,height:1000});await page.goto(base+'/settings');await page.locator('#token').fill(adminToken);await page.locator('#login button').click();await page.locator('[data-section-button="integrations"]').click();await page.waitForSelector('#booking-save');assert.equal(await page.locator('#booking-enabled').isChecked(),true);await page.locator('#booking-horizonDays').fill('7');await page.locator('#booking-save').click();await page.waitForFunction(()=>document.querySelector('#booking-settings [role="status"]').textContent.includes('Reglas guardadas'));assert.equal(f.repo.bookingSettings().horizonDays,7);
 if(process.env.SCREENSHOT_DIR){mkdirSync(process.env.SCREENSHOT_DIR,{recursive:true});await page.locator('#booking-settings').screenshot({path:join(process.env.SCREENSHOT_DIR,'booking-settings.png')});}
 await page.setViewportSize({width:390,height:844});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));assert.deepEqual(errors,[]);
 // Optional keyboard is enabled in the real configuration UI, with isolated data.
 await page.locator('[data-section-button="experience"]').click();await page.locator('[name="experience.touchKeyboard"]').check();await page.locator('#save').click();await page.waitForFunction(()=>document.querySelector('#saved').textContent.includes('Configuración guardada'));
 await page.goto(base);await page.locator('#start').click();await page.locator('#accept-session').click();await page.waitForFunction(()=>document.querySelector('#mic').getAttribute('aria-pressed')==='true');await page.locator('#call-booking').click();await page.getByRole('button',{name:'Reservar y confirmar cita',exact:true}).click();await page.getByRole('button',{name:'Clase práctica · 60 min',exact:true}).click();await page.locator('.slot:not(:disabled)').first().click();
 const keyboard=page.locator('#touch-keyboard'),editor=page.locator('#touch-keyboard-value'),key=char=>keyboard.getByRole('button',{name:char,exact:true});
 await page.locator('[name="customerName"]').click();assert.equal(await keyboard.isVisible(),false);await page.getByRole('button',{name:'Teclado para Nombre y apellido',exact:true}).click();await page.waitForSelector('#touch-keyboard:not([hidden])');assert.equal(await page.evaluate(()=>window.__recognition.active),false);
 for(const ch of 'josé')await key(ch).click();await keyboard.getByRole('button',{name:'Mayúsculas',exact:true}).click();await key('A').click();await keyboard.getByRole('button',{name:'Borrar carácter',exact:true}).click();await key('Espacio').click();await key('Ñ').click();
 assert.equal(await page.locator('[name="customerName"]').inputValue(),'josé Ñ');await editor.evaluate(el=>el.setSelectionRange(0,4));await key('J').click();assert.equal(await editor.inputValue(),'J Ñ');await page.getByRole('button',{name:'Teclado para Nombre y apellido',exact:true}).click();assert.equal(await keyboard.isVisible(),false);assert.equal(await editor.inputValue(),'');
 await page.getByRole('button',{name:'Teclado para Correo electrónico',exact:true}).click();for(const ch of 'voz@example.test')await key(ch).click();assert.equal(await page.locator('[name="email"]').inputValue(),'voz@example.test');assert.equal(await page.locator('[name="email"]').evaluate(el=>el.validity.valid),true);
 assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));const bounds=await keyboard.boundingBox();assert.ok(bounds.x>=0&&bounds.x+bounds.width<=391&&bounds.width<=391);
 if(process.env.SCREENSHOT_DIR)await page.screenshot({path:join(process.env.SCREENSHOT_DIR,'touch-keyboard.png')});
 await page.keyboard.press('Escape');await page.waitForFunction(()=>document.querySelector('#touch-keyboard').hidden);assert.equal(await keyboard.isVisible(),false);assert.equal(await page.locator('#booking-dialog').getAttribute('open'),'');assert.equal(f.events.size,0);assert.equal(mails.length,2);
 // Timeout clears the editable copy too, and never sends or books from the keyboard.
 await page.getByRole('button',{name:'Teclado para Correo electrónico',exact:true}).click();await page.evaluate(()=>{const now=Date.now.bind(Date);Date.now=()=>now()+61000;});await page.waitForFunction(()=>!document.body.classList.contains('voice-call'));assert.equal(await editor.inputValue(),'');assert.equal(await keyboard.isVisible(),false);assert.equal(await page.locator('[name="email"]').count(),0);
 // Chat editing honors maximum length; closing never submits a message.
 await page.setViewportSize({width:1360,height:1000});await page.goto(base);await page.locator('#home-chat').click();await page.locator('#message').evaluate(el=>el.maxLength=3);const chatsBefore=chats.length;await page.getByRole('button',{name:'Teclado para Su consulta',exact:true}).click();for(const ch of 'abcd')await key(ch).click();assert.equal(await page.locator('#message').inputValue(),'abc');await key('Listo ✓').click();assert.equal(chats.length,chatsBefore);
 // Video provider is fully simulated; test the same form without paid sessions.
 await page.addInitScript(()=>{
  class Socket{readyState=1;bufferedAmount=0;handlers={};constructor(){setTimeout(()=>this.emit({type:'session.state_updated',state:'connected'}),20);}addEventListener(n,fn){this.handlers[n]=fn;}emit(e){this.handlers.message?.({data:JSON.stringify(e)});}send(text){const p=JSON.parse(text);if(p.type==='agent.speak_end'){this.emit({type:'agent.speak_started',source_event_id:p.event_id});setTimeout(()=>this.emit({type:'agent.speak_ended',source_event_id:p.event_id}),20);}}close(){this.readyState=3;this.handlers.close?.();}}
  window.WebSocket=Socket;
  class Room{handlers={};on(n,fn){this.handlers[n]=fn;}async connect(){window.__videoRoom=this;const c=document.createElement('canvas');c.width=640;c.height=360;const ctx=c.getContext('2d');this.timer=setInterval(()=>{ctx.fillStyle='#426950';ctx.fillRect(0,0,640,360);},50);this.stream=c.captureStream(10);this.handlers.track({kind:'video',attach:el=>{el.srcObject=this.stream;}});this.handlers.track({kind:'audio',attach(){}});}async startAudio(){}async disconnect(){clearInterval(this.timer);this.stream?.getTracks().forEach(t=>t.stop());}}
  window.LivekitClient={Room,RoomEvent:{TrackSubscribed:'track',DataReceived:'data',Disconnected:'disconnected'}};
 });
 await page.goto(base);await page.locator('#start-video').click();await page.locator('#accept-session').click();await page.waitForSelector('#avatar.video-ready');await page.locator('#call-booking').click();await page.getByRole('button',{name:'Reservar y confirmar cita',exact:true}).click();await page.getByRole('button',{name:'Clase práctica · 60 min',exact:true}).click();await page.locator('.slot:not(:disabled)').first().click();await page.getByRole('button',{name:'Teclado para Nombre y apellido',exact:true}).click();await key('a').click();assert.equal(await page.locator('[name="customerName"]').inputValue(),'a');await key('Listo ✓').click();
 await page.evaluate(()=>window.__videoRoom.handlers.disconnected());await page.waitForFunction(()=>!document.body.classList.contains('video-first'));assert.equal(await page.locator('#booking-dialog').evaluate(el=>el.open),true);assert.equal(await page.locator('[name="customerName"]').inputValue(),'a');assert.ok(videoStops.length);await page.keyboard.press('Escape');
 // Turning the optional feature off restores the native email input mode.
 const setting=repo.getCenterSettings();setting.configuration.experience.touchKeyboard=false;repo.saveConfiguration(setting.revision,{profile:setting.profile,configuration:setting.configuration});await page.goto(base);await page.locator('#home-chat').click();await page.locator('#message').click();assert.equal(await keyboard.isVisible(),false);assert.notEqual(await page.locator('#message').getAttribute('inputmode'),'none');
 // Conversational availability offers live options, remembers changes, and only opens the form.
 const conversationDate=(await booking.availability('road-test')).slots[0].slice(0,10);
 await page.goto(base);await page.locator('#home-chat').click();await page.locator('#message').fill('Quiero una clase práctica el '+conversationDate+' por la tarde');await page.locator('#send').click();await page.locator('#accept-session').click();await page.waitForSelector('.agenda-options button');assert.equal(await page.locator('.agenda-options button').count(),3);
 await page.locator('#message').fill('mejor por la mañana');await page.locator('#send').click();await page.waitForFunction(()=>document.querySelectorAll('.agenda-options button').length===6);
 await page.locator('#message').fill('la segunda');await page.locator('#send').click();await page.waitForSelector('#booking-content [name="customerName"]');assert.equal(f.events.size,0);assert.equal(mails.length,2);assert.match(await page.locator('.booking-summary').innerText(),/Clase práctica/);await page.keyboard.press('Escape');
 await page.goto(base);await page.locator('#start').click();await page.locator('#accept-session').click();await page.waitForFunction(()=>document.querySelector('#mic').getAttribute('aria-pressed')==='true');
 const say=async text=>{await page.waitForFunction(()=>document.querySelector('#mic').getAttribute('aria-pressed')==='true');await page.evaluate(text=>{const r=window.__recognition,result=[{transcript:text}];result.isFinal=true;r.onresult({results:[result]});r.onend?.();},text);};
 await say('Quiero una clase práctica el '+conversationDate+' por la tarde');await page.waitForSelector('.agenda-options button');await say('mejor por la mañana');await page.waitForFunction(()=>document.querySelectorAll('.agenda-options button').length===6);await say('la primera');await page.waitForSelector('#booking-content [name="customerName"]');assert.equal(await page.evaluate(()=>window.__recognition.active),false);assert.equal(f.events.size,0);await page.keyboard.press('Escape');await page.locator('#call-hangup').click();
 assert.deepEqual(errors,[]);
 console.log('Reservas E2E: home y llamada por voz, día/hora, correo válido, pausa y reanudación del micrófono, confirmación, cancelación, varios servicios, inactividad, privacidad y móvil. Proveedor simulado, sin gastos ni citas reales.');
}finally{await browser.close();await new Promise(r=>app.close(r));f.repo.close();}
