/**
 * NEXO · GUÍA DEL MÓDULO: tests/google-calendar.test.js
 * Pruebas unitarias y de integración de google calendar.
 * Entrada: Casos y fixtures definidos en este archivo; dependencias simuladas cuando se inyectan.
 * Salida: Aserciones aprobadas o fallo con ubicación; los E2E pueden generar capturas locales.
 * Estado importante: fixture prepara escenario; assert compara resultado esperado; limpieza de
 * recursos evita contaminación entre casos.
 * Efectos y límites: Revisar fixtures y proveedores inyectados antes de ejecutar; los dobles
 * aíslan servicios externos. No usar la base de producción como fixture.
 * Ruta de aprendizaje: docs/23-manual-desarrollador-junior.md y docs/41-mapa-codigo-fuente.md.
 */

import test from 'node:test';
import assert from 'node:assert/strict';
import {once} from 'node:events';
import {mkdtempSync,rmSync,existsSync,readFileSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join,resolve,sep} from 'node:path';
import {createApp} from '../server/app.js';
import {createRepository} from '../server/db.js';
import {GoogleCalendarService} from '../server/providers/google-calendar.js';
import {schoolCenter} from '../server/center.js';
import {readConfig} from '../server/config.js';
import {calendarFixture} from './calendar-fixture.js';
const admin='calendar-administrator-fixture-token';
function fixture(t){const f=calendarFixture();t.after(()=>f.repo.close());return f;}
test('Calendar sin credenciales informa pendiente y nunca consulta Google',t=>{const f=fixture(t),s=new GoogleCalendarService({repository:f.repo});assert.equal(s.status().configured,false);assert.throws(()=>s.begin(),/Configure GOOGLE/);assert.equal(f.calls.length,0);});
test('OAuth usa estado, PKCE, permisos limitados, vinculación de navegador y un único uso',async t=>{
 const f=fixture(t),start=f.service.begin(),url=new URL(start.url),state=url.searchParams.get('state');assert.equal(url.hostname,'accounts.google.com');assert.equal(url.searchParams.get('code_challenge_method'),'S256');assert.equal(url.searchParams.get('access_type'),'offline');assert.doesNotMatch(url.searchParams.get('scope'),/gmail|drive/);
 await assert.rejects(f.service.complete({state,code:'code'},'wrong-browser'),/otro navegador/);assert.equal(f.calls.length,0);
 await f.service.complete({state,code:'code'},start.binding);assert.ok(f.calls[0].body.code_verifier);await assert.rejects(f.service.complete({state,code:'code'},start.binding),/venció/);
 const stored=f.repo.readCalendarConnection().tokens;assert.doesNotMatch(stored,/secret|access_token|refresh_token/);assert.doesNotMatch(JSON.stringify(f.service.status()),/secret|refresh_token|access_token|clientSecret/);
});
test('OAuth vencido, cancelado o con permisos parciales no conecta',async t=>{
 const f=fixture(t),start=f.service.begin();f.advance(300001);await assert.rejects(f.service.complete({state:new URL(start.url).searchParams.get('state'),code:'code'},start.binding));
 const next=f.service.begin();await assert.rejects(f.service.complete({state:new URL(next.url).searchParams.get('state'),error:'access_denied'},next.binding),/No se autorizó/);
 f.flags.partialScope=true;await assert.rejects(f.authorize(),/ambos/);assert.equal(f.service.status().connected,false);
 f.flags.partialScope=false;f.flags.noRefresh=true;await assert.rejects(f.authorize());assert.equal(f.repo.readCalendarConnection().tokens,null);
});
test('calendarios paginados y nombres repetidos conservan ID; solo lectura rechazado',async t=>{const f=fixture(t);await f.authorize();const list=await f.service.calendars();assert.equal(list.length,3);assert.equal(list.filter(c=>c.name==='Mogollon Method').length,2);await assert.rejects(f.service.select(list[2].id),/solo lectura/);await f.service.select(list[1].id);assert.equal(f.service.status().selected.id,list[1].id);});
test('lectura usa exclusivamente calendario seleccionado y no devuelve datos de citas',async t=>{const f=fixture(t);await f.authorize();const id=f.calendars[1].id;await f.service.select(id);await assert.rejects(f.service.check(f.calendars[0].id),/cambió/);const check=await f.service.check(id);assert.equal(check.eventsNext7Days,1);assert.equal(check.timeZone,'America/New_York');assert.doesNotMatch(JSON.stringify(check),/existing-event/);assert.ok(f.calls.filter(c=>c.path.includes('/events')).every(c=>decodeURIComponent(c.path).includes(id)));});
test('prueba crea, lee y elimina solo evento propio; sin invitados ni bloqueo',async t=>{const f=fixture(t);await f.authorize();const id=f.calendars[1].id;await f.service.select(id);const result=await f.service.test(id);assert.equal(result.cleaned,true);assert.equal(f.events.size,0);assert.equal(f.repo.pendingCalendarTests().length,0);const create=f.calls.find(c=>c.method==='POST'&&c.path.endsWith('/events'));assert.equal(create.body.transparency,'transparent');assert.equal(create.body.reminders.useDefault,false);assert.equal(create.body.attendees,undefined);assert.match(create.body.summary,/PRUEBA NEXO/);assert.match(create.url,/sendUpdates=none/);assert.ok(f.calls.filter(c=>c.path.includes('/events')).every(c=>decodeURIComponent(c.path).includes(id)));});
test('fallo de limpieza queda persistido y se puede recuperar sin crear duplicados',async t=>{const f=fixture(t);await f.authorize();const id=f.calendars[1].id;await f.service.select(id);f.flags.deleteFails=true;await assert.rejects(f.service.test(id),/limpiar/);assert.equal(f.repo.pendingCalendarTests().length,1);await assert.rejects(f.service.test(id),/pendiente/);await assert.rejects(f.service.select(f.calendars[0].id),/pendientes/);await assert.rejects(f.service.disconnect(),/pendiente/);f.flags.deleteFails=false;await f.service.cleanup();assert.equal(f.events.size,0);assert.equal(f.repo.pendingCalendarTests().length,0);});
test('respuesta incierta después de insertar mantiene identificación para limpiar',async t=>{const f=fixture(t);await f.authorize();await f.service.select(f.calendars[1].id);f.flags.insertUncertain=true;await assert.rejects(f.service.test(f.calendars[1].id),/confirmar la creación/);assert.equal(f.repo.pendingCalendarTests().length,1);assert.equal(f.events.size,1);await f.service.cleanup();assert.equal(f.events.size,0);});
test('nunca elimina un evento cuyo marcador no corresponde a Nexo',async t=>{const f=fixture(t);await f.authorize();await f.service.select(f.calendars[1].id);f.flags.deleteFails=true;await assert.rejects(f.service.test(f.calendars[1].id));const [key,event]=[...f.events][0];f.events.set(key,{...event,extendedProperties:{private:{nexoTest:'different'}}});const before=f.calls.filter(c=>c.method==='DELETE').length;await assert.rejects(f.service.cleanup(),/no coincide/);assert.equal(f.calls.filter(c=>c.method==='DELETE').length,before);assert.equal(f.events.size,1);});
test('renueva token caducado, reintenta 401 una vez y no filtra errores de Google',async t=>{const f=fixture(t);await f.authorize();f.advance(3600000);await f.service.calendars();assert.ok(f.calls.some(c=>c.body?.grant_type==='refresh_token'));f.flags.unauthorizedOnce=true;await f.service.calendars();f.flags.forbidden=true;await assert.rejects(f.service.calendars(),e=>e.status===403&&!e.message.includes('private-google-diagnostic'));});
test('desconectar revoca autorización y elimina tokens locales incluso si Google falla',async t=>{const f=fixture(t);await f.authorize();f.flags.revokeFails=true;const r=await f.service.disconnect();assert.equal(r.revoked,false);assert.equal(r.connected,false);assert.equal(f.repo.readCalendarConnection().tokens,null);assert.ok(f.calls.some(c=>c.path==='/revoke'));});
test('autorización retirada exige reconectar y conserva prueba pendiente para recuperación',async t=>{const f=fixture(t);await f.authorize();await f.service.select(f.calendars[1].id);f.flags.deleteFails=true;await assert.rejects(f.service.test(f.calendars[1].id));f.advance(3600000);f.flags.invalidGrant=true;await assert.rejects(f.service.calendars(),/venció/);assert.equal(f.service.status().needsReconnect,true);assert.equal(f.service.status().connected,false);f.flags.invalidGrant=false;f.flags.deleteFails=false;await f.authorize();assert.equal(f.repo.pendingCalendarTests().length,1);await f.service.cleanup();assert.equal(f.events.size,0);});
test('creación incierta ausente espera antes de confirmar limpieza',async t=>{const f=fixture(t);await f.authorize();await f.service.select(f.calendars[1].id);f.flags.insertUncertain=true;await assert.rejects(f.service.test(f.calendars[1].id));f.events.clear();await assert.rejects(f.service.cleanup(),/dos minutos/);assert.equal(f.repo.pendingCalendarTests().length,1);f.advance(120001);await f.service.cleanup();assert.equal(f.repo.pendingCalendarTests().length,0);});
test('no permite cambiar calendario ni desconectar durante una prueba en curso',async t=>{const f=fixture(t);await f.authorize();await f.service.select(f.calendars[1].id);let release,entered;const ready=new Promise(r=>entered=r),original=f.service.fetch;f.service.fetch=async(url,options)=>{if(options.method==='POST'&&String(url).includes('/events?')){entered();await new Promise(r=>release=r);}return original(url,options);};const running=f.service.test(f.calendars[1].id);await ready;await assert.rejects(f.service.select(f.calendars[0].id),/otra operación/);await assert.rejects(f.service.disconnect(),/otra operación/);release();await running;assert.equal(f.service.status().selected.id,f.calendars[1].id);});
test('cifrado y calendario seleccionado sobreviven reinicio con clave local; otra clave falla',async()=>{
 const directory=mkdtempSync(join(tmpdir(),'nexo-calendar-')),path=join(directory,'app.sqlite'),keyPath=join(directory,'calendar.key');let repo;
 try{repo=createRepository(path);const f=calendarFixture({repo}),config={...f.config,keyPath};let s=new GoogleCalendarService({repository:repo,config,fetchImpl:f.fetchImpl});const start=s.begin();await s.complete({state:new URL(start.url).searchParams.get('state'),code:'code'},start.binding);await s.select(f.calendars[1].id);assert.ok(existsSync(keyPath));assert.equal(readFileSync(keyPath).length,32);repo.close();repo=createRepository(path);s=new GoogleCalendarService({repository:repo,config,fetchImpl:f.fetchImpl});assert.equal(s.status().connected,true);assert.equal(s.status().selected.id,f.calendars[1].id);const wrong=new GoogleCalendarService({repository:repo,config,key:Buffer.alloc(32)});assert.equal(wrong.status().needsReconnect,true);const changed=new GoogleCalendarService({repository:repo,config:{...config,clientId:'different'},fetchImpl:f.fetchImpl});assert.equal(changed.status().needsReconnect,true);
 }finally{repo?.close();assert.ok(resolve(directory).startsWith(resolve(tmpdir())+sep));rmSync(directory,{recursive:true,force:true});}
});
test('configuración deriva retorno local y rechaza otro origen o ruta',()=>{const base={AI_PROVIDER:'demo',PORT:'3000'};assert.equal(readConfig(base).googleCalendar.redirectUri,'http://localhost:3000/api/calendar/oauth/callback');assert.throws(()=>readConfig({...base,GOOGLE_REDIRECT_URI:'https://other.test/callback'}),/coincidir/);});
test('API protege operaciones, callback requiere cookie vinculada y público no ve credenciales',async t=>{
 const f=calendarFixture();const app=createApp({repository:f.repo,config:{provider:'demo',center:schoolCenter,adminToken:admin,googleCalendar:f.config,sessionTtlMs:300000},calendar:f.service,ai:{reply:async()=>({text:'demo'})},localTts:{status:()=>({available:false}),close(){},stop(){}},liveAvatar:{status:()=>({configured:false}),async stop(){},async close(){}}});app.listen(0,'127.0.0.1');await once(app,'listening');t.after(async()=>{await new Promise(r=>app.close(r));f.repo.close();});const base='http://localhost:'+app.address().port;f.config.redirectUri=base+'/api/calendar/oauth/callback';
 for(const [method,path]of [['GET',''],['GET','/calendars'],['POST','/connect'],['PUT','/selection'],['POST','/check'],['POST','/test'],['POST','/cleanup'],['DELETE','']])assert.equal((await fetch(base+'/api/admin/calendar'+path,{method,headers:{'Content-Type':'application/json'},...(['POST','PUT'].includes(method)?{body:'{}'}:{})})).status,401);
 assert.equal(f.calls.length,0);const connect=await fetch(base+'/api/admin/calendar/connect',{method:'POST',headers:{Authorization:'Bearer '+admin,'Content-Type':'application/json'},body:'{}'});assert.equal(connect.status,200);const cookie=connect.headers.get('set-cookie').split(';')[0],auth=await connect.json(),state=new URL(auth.url).searchParams.get('state');assert.match(connect.headers.get('set-cookie'),/HttpOnly; SameSite=Lax/);
 const callback=base+'/api/calendar/oauth/callback?state='+state+'&code=code';const invalid=await fetch(callback,{redirect:'manual'});assert.match(invalid.headers.get('location'),/failed/);assert.equal(f.service.status().connected,false);
 const valid=await fetch(callback,{redirect:'manual',headers:{cookie}});assert.match(valid.headers.get('location'),/connected/);assert.equal(f.service.status().connected,true);
 const publicData=await fetch(base+'/api/config').then(r=>r.text());assert.doesNotMatch(publicData,/secret|refresh_token|clientSecret|client-id|calendarList/);
 const settings=await fetch(base+'/api/admin/configuration',{headers:{Authorization:'Bearer '+admin}}).then(r=>r.text());assert.doesNotMatch(settings,/secret-refresh|secret-access|secret-client/);
});
